### ISSUE TITLE
Implement the ability to scroll though photos (Android)

### ISSUE THREAD

**Issue by adamclark2** [adamclark2/Photos#3]
Users would like to scroll through a list of photos. 

This ticket is *done* when
   * A user can scroll through a list of photos (on Android)

### Prereqisite: #1 must be completed first

**Comment by Noah-Rausch** [comment]
Have the pure UI done, just setting up libraries to make the async HTTP call easier.

**Comment by NoahRausch** [comment]
Good news, the android client now works, connects to the backend, and loads a bunch of images!  The image below is just a feed of the same image repeating, but each image is loaded independently from the server

**Comment by NoahRausch** [comment]
![emulator_screenshot](https://user-images.githubusercontent.com/16840325/37560910-7fed87da-2a17-11e8-9f6e-c138cfcdf4ff.png)
